name: about_me
author: Dylan Powers
homepage: me.dylankpowers.com
description: A dart app showcasing a little about me
dependencies:
  barback: any
  polymer: any
transformers:
- polymer:
    entry_points: index.html
