name: about_me
author: Dylan Powers
homepage: me.dylankpowers.com
description: A dart app showcasing a little about me
dependencies:
  polymer: ">=0.11.0 <0.12.0"
transformers:
- polymer:
    entry_points: web/index.html
