name: about_me
author: Dylan Powers
homepage: me.dylankpowers.com
description: A dart app showcasing a little about me
dependencies:
  polymer: '0.9.2+4'
transformers:
- polymer:
    entry_points: web/index.html
