name: about_me
author: Dylan Powers
homepage: me.dylankpowers.com
description: A dart app showcasing a little about me
environment:
  sdk: ">=1.7.0-dev"
dependencies:
  angular: ">=1.0.0 <2.0.0"
  polymer: ">=0.15.0 <0.16.0"
  paper_elements: any
dev_dependencies:
  unittest: ">=0.11.0 <0.12.0"
dependency_overrides:
  args: ">=0.11.0 <0.12.0"
  code_transformers: ">=0.2.3 <0.3.0"
  html5lib: ">=0.12.0 <0.13.0"
  observe: ">=0.11.0 <0.12.0"
transformers:
- polymer:
    entry_points:
      - web/index.html
      - test/main_test.html
- angular