name: about_me
author: Dylan Powers
homepage: me.dylankpowers.com
description: A dart app showcasing a little about me
environment:
  sdk: ">=1.8.0-dev"
dependencies:
  polymer: ">=0.15.0 <0.16.0"
  paper_elements: any
dev_dependencies:
  guinness: ">=0.1.16 <0.2.0"
  sass: ">=0.4.2 <0.5.0"
  unittest: any
dependency_overrides:
  unittest:
    git: https://github.com/dylanPowers/dart-unittest.git
transformers:
- sass
- polymer:
    entry_points:
      - web/index.html
      - test/index.html