name: about_me
author: Dylan Powers
homepage: me.dylankpowers.com
description: A dart app showcasing a little about me
environment:
  sdk: ">=1.7.0-dev"
dependencies:
  polymer: ">=0.15.0 <0.16.0"
  paper_elements: any
dev_dependencies:
  unittest: ">=0.11.0 < 0.12.0"
transformers:
- polymer:
    entry_points:
      - web/index.html
      - test/main_test.html
